export type HeroInfo = { ko: string; slug: string };

export const HEROES: Record<string, HeroInfo> = {
  Ana: { ko: "아나", slug: "ana" },
  Anran: { ko: "안란", slug: "anran" },
  Ashe: { ko: "애쉬", slug: "ashe" },
  Baptiste: { ko: "바티스트", slug: "baptiste" },
  Bastion: { ko: "바스티온", slug: "bastion" },
  Brigitte: { ko: "브리기테", slug: "brigitte" },
  Cassidy: { ko: "캐서디", slug: "cassidy" },
  "D.Va": { ko: "디바", slug: "d.va" },
  Domina: { ko: "도미나", slug: "domina" },
  Doomfist: { ko: "둠피스트", slug: "doomfist" },
  Echo: { ko: "에코", slug: "echo" },
  Emre: { ko: "엠레", slug: "emre" },
  Freja: { ko: "프레야", slug: "freja" },
  Genji: { ko: "겐지", slug: "genji" },
  Hanzo: { ko: "한조", slug: "hanzo" },
  Hazard: { ko: "해저드", slug: "hazard" },
  Illari: { ko: "일리아리", slug: "illari" },
  "Jetpack Cat": { ko: "제트팩 캣", slug: "jetpack-cat" },
  "Junker Queen": { ko: "정커 퀸", slug: "junker-queen" },
  Junkrat: { ko: "정크랫", slug: "junkrat" },
  Juno: { ko: "주노", slug: "juno" },
  Kiriko: { ko: "키리코", slug: "kiriko" },
  Lifeweaver: { ko: "라이프위버", slug: "lifeweaver" },
  Lucio: { ko: "루시우", slug: "lucio" },
  Mauga: { ko: "마우가", slug: "mauga" },
  Mei: { ko: "메이", slug: "mei" },
  Mercy: { ko: "메르시", slug: "mercy" },
  Mizuki: { ko: "미즈키", slug: "mizuki" },
  Moira: { ko: "모이라", slug: "moira" },
  Orisa: { ko: "오리사", slug: "orisa" },
  Pharah: { ko: "파라", slug: "pharah" },
  Ramattra: { ko: "라마트라", slug: "ramattra" },
  Reaper: { ko: "리퍼", slug: "reaper" },
  Reinhardt: { ko: "라인하르트", slug: "reinhardt" },
  Roadhog: { ko: "로드호그", slug: "roadhog" },
  Sierra: { ko: "시에라", slug: "sierra" },
  Sigma: { ko: "시그마", slug: "sigma" },
  Sojourn: { ko: "소전", slug: "sojourn" },
  "Soldier:76": { ko: "솔저: 76", slug: "soldier-76" },
  Sombra: { ko: "솜브라", slug: "sombra" },
  Symmetra: { ko: "시메트라", slug: "symmetra" },
  Torbjorn: { ko: "토르비욘", slug: "torbjorn" },
  Tracer: { ko: "트레이서", slug: "tracer" },
  Vendetta: { ko: "벤데타", slug: "vendetta" },
  Venture: { ko: "벤처", slug: "venture" },
  Widowmaker: { ko: "위도우메이커", slug: "widowmaker" },
  Winston: { ko: "윈스턴", slug: "winston" },
  "Wrecking Ball": { ko: "레킹볼", slug: "wrecking-ball" },
  Wuyang: { ko: "우양", slug: "wuyang" },
  Zarya: { ko: "자리야", slug: "zarya" },
  Zenyatta: { ko: "젠야타", slug: "zenyatta" },
};

export function getHero(name: string): HeroInfo {
  return HEROES[name] ?? { ko: name, slug: name.toLowerCase() };
}
